[package]
name = "ldiff"
version = "0.1.0"
authors = ["Martin Hagström <martin.hagstrom@diffinder.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
